<a href="https://colab.research.google.com/github/utkarsh0702/Tensorflow/blob/master/TensorFlow1_Basics_of_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
print(tf.__version__)

2.2.0-rc2


In [3]:
#Key value pair using keras in nlp
sentences=[
           'I love my dog',
           'I love my cat',
           'You love my dog!'
]
token= Tokenizer(num_words=100)
token.fit_on_texts(sentences)
word_index= token.word_index
print(word_index)

{'love': 1, 'my': 2, 'i': 3, 'dog': 4, 'cat': 5, 'you': 6}


In [4]:
# Sequencing the key value pair
sentences=[
           'I love my dog',
           'I love my cat',
           'You love my dog!',
           'Do you think my dog is amazing?'
]
token= Tokenizer(num_words=100)
token.fit_on_texts(sentences)
word_index= token.word_index
sequence= token.texts_to_sequences(sentences)
print(word_index)
print(sequence)

{'my': 1, 'love': 2, 'dog': 3, 'i': 4, 'you': 5, 'cat': 6, 'do': 7, 'think': 8, 'is': 9, 'amazing': 10}
[[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]


In [6]:
#for the unseen data to avoid conflicts and loss
sentences=[
           'I love my dog',
           'I love my cat',
           'You love my dog!',
           'Do you think my dog is amazing?'
]
test_sentences=[
                 'I want my cycle',
                 'Dog is my favorite animal'
]
token= Tokenizer(num_words=100, oov_token='<OOV>')
token.fit_on_texts(sentences)
word_index= token.word_index
sequence= token.texts_to_sequences(sentences)
# for testing on unseen words and sentences
test_sequence= token.texts_to_sequences(test_sentences)
print(word_index)
print('--------------------Train Data----------------------')
print(sequence)
print('---------------------Test Data----------------------')
print(test_sequence)

{'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
--------------------Train Data----------------------
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]
---------------------Test Data----------------------
[[5, 1, 2, 1], [4, 10, 2, 1, 1]]


In [8]:
#Padding to make word sequence of each letter of equal length
sentences=[
           'I love my dog',
           'I love my cat',
           'You love my dog!',
           'Do you think my dog is amazing?'
]

token= Tokenizer(num_words=100, oov_token='<OOV>')
token.fit_on_texts(sentences)
word_index= token.word_index
sequence= token.texts_to_sequences(sentences)
#padding
padded= pad_sequences(sequence)
#padding from the end
padded1= pad_sequences(sequence, padding='post')
#padding with maximum length
padded2= pad_sequences(sequence, maxlen=5)
print(word_index)
print(sequence)
print('---------------Padding------------------')
print(padded)
print('---------------Padding from the end------------')
print(padded1)
print('---------------Padding with max length------------')
print(padded2)

{'<OOV>': 1, 'my': 2, 'love': 3, 'dog': 4, 'i': 5, 'you': 6, 'cat': 7, 'do': 8, 'think': 9, 'is': 10, 'amazing': 11}
[[5, 3, 2, 4], [5, 3, 2, 7], [6, 3, 2, 4], [8, 6, 9, 2, 4, 10, 11]]
---------------Padding------------------
[[ 0  0  0  5  3  2  4]
 [ 0  0  0  5  3  2  7]
 [ 0  0  0  6  3  2  4]
 [ 8  6  9  2  4 10 11]]
---------------Padding from the end------------
[[ 5  3  2  4  0  0  0]
 [ 5  3  2  7  0  0  0]
 [ 6  3  2  4  0  0  0]
 [ 8  6  9  2  4 10 11]]
---------------Padding with max length------------
[[ 0  5  3  2  4]
 [ 0  5  3  2  7]
 [ 0  6  3  2  4]
 [ 9  2  4 10 11]]
